# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pg_hstore}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{Marc Chung}]
  s.date = %q{2011-06-16}
  s.description = %q{Ever wanted to use nosql with pgsql? Now you can}
  s.email = %q{mchung@gmail.com}
  s.executables = [%q{autospec}, %q{htmldiff}, %q{jeweler}, %q{ldiff}, %q{rake}, %q{rcov}, %q{rspec}, %q{yard}, %q{yardoc}, %q{yri}]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    ".document",
    ".rspec",
    ".rvmrc",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "TODO",
    "VERSION",
    "bin/autospec",
    "bin/htmldiff",
    "bin/jeweler",
    "bin/ldiff",
    "bin/rake",
    "bin/rcov",
    "bin/rspec",
    "bin/yard",
    "bin/yardoc",
    "bin/yri",
    "contrib/hstore/hstore-1.15.sql",
    "contrib/hstore/hstore_examples.data",
    "contrib/hstore/hstore_examples.sql",
    "database.yml",
    "lib/pg_hstore.rb",
    "lib/pg_hstore/active_record/postgresql_adapter.rb",
    "lib/pg_hstore/active_record/postgresql_adapter/postgresql_column.rb",
    "lib/pg_hstore/active_record/postgresql_adapter/table_definition.rb",
    "lib/pg_hstore/active_record/schema_dumper.rb",
    "lib/pg_hstore/hstore_class_methods.rb",
    "lib/pg_hstore/hstore_instance_methods.rb",
    "lib/pg_hstore/hstore_serialize.rb",
    "lib/pg_hstore/hstore_type.rb",
    "lib/pg_hstore/pg_hstore_record.rb",
    "lib/pg_hstore/railties/hstore-1.15.sql",
    "lib/pg_hstore/railties/railtie.rb",
    "pg_hstore.gemspec",
    "spec/hstore_spec.rb",
    "spec/pg_hstore_enemy_spec.rb",
    "spec/pg_hstore_record_spec.rb",
    "spec/pg_hstore_spec.rb",
    "spec/schema_dumper_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/mchung/pg_hstore}
  s.licenses = [%q{MIT}]
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.5}
  s.summary = %q{Use the hstore with ActiveRecord}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<pg>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<yard>, [">= 0"])
      s.add_development_dependency(%q<bundler>, [">= 0"])
      s.add_development_dependency(%q<jeweler>, [">= 0"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<activesupport>, ["= 3.1.0.rc4"])
      s.add_development_dependency(%q<activerecord>, ["= 3.1.0.rc4"])
    else
      s.add_dependency(%q<pg>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<yard>, [">= 0"])
      s.add_dependency(%q<bundler>, [">= 0"])
      s.add_dependency(%q<jeweler>, [">= 0"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<activesupport>, ["= 3.1.0.rc4"])
      s.add_dependency(%q<activerecord>, ["= 3.1.0.rc4"])
    end
  else
    s.add_dependency(%q<pg>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<yard>, [">= 0"])
    s.add_dependency(%q<bundler>, [">= 0"])
    s.add_dependency(%q<jeweler>, [">= 0"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<activesupport>, ["= 3.1.0.rc4"])
    s.add_dependency(%q<activerecord>, ["= 3.1.0.rc4"])
  end
end

